[package]
name = "hapir-shared"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sys-locale = { workspace = true }
ts-rs = { workspace = true }
uuid = { version = "1", features = ["v4"] }
